### PR TITLE
Improve string template engine and name option

### PR DESCRIPTION
**Pull request by cervengoc**
First of all, thank you for this package, really useful and gives great connection between `knockout` and `webpack`.

I've implemented the following improvements.

- Used the latest `knockout` code from default `makeTemplateSource`, so we have error handling, etc.
- Improved the `name` option to
  - allow using `[name]` or any other placeholder.
  - allow passing a callback having a path info parameter.

Could you please review the changes and merge/release this if you agree?

### CODE REVIEW

**Review by chadly — CHANGES_REQUESTED** [review]
Thanks! I like these improvements. Could you update the documentation (the README) as well to show some examples of how this could be used?

**Comment by cervengoc** [comment]
Hi @chadly, sorry for disappearing for a while. I've rethought the "name as a callback" option to keep it simple, so we pass only the full path as a string, and the consumer can do whatever he wants to with it.

Also, I've introduced a new option for case-insensitivity, please share your thoughts on that. Sorry for reusing this PR for that.

I've updated the documentation to reflect to these changes.

**Comment by cervengoc** [comment]
@chadly, could you please merge this? I'm partially blocked until this is merged, I would really appreciate your cooperation. Thank you!

**Comment by cervengoc** [comment]
@chadly Any news? 
I'm happy to help with maintaining this project if you don't have resources.

**Comment by garrettbryan** [comment]
Thanks for the loader, it's just what I needed!

**Comment by kapral** [comment]
@chadly Can this be merged please? Thanks

**Review by chadly — APPROVED** [review]

**Pull request merged**
